CREATE TABLE `binary`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`description` VARCHAR(10),
	`id` BIGINT NOT NULL,
	`image` LONGBLOB,
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`SoftDeleteFlag` BOOLEAN,
	PRIMARY KEY(`id`)
);
ALTER TABLE `binary`
	ADD CONSTRAINT `c3b930f1984cd56b84248126d20283` UNIQUE KEY(`id`);
